"""Exact gradients via the parameter-shift rule.

RY(theta) and RZ(theta) are both generated by an operator with eigenvalues
+-1/2, so for any cost function C(theta) built from expectation values of
such a circuit,

    dC/dtheta_k = [C(theta + (pi/2) e_k) - C(theta - (pi/2) e_k)] / 2

is *exact* (not a finite-difference approximation) -- see Mitarai et al.
2018 / Schuld et al. 2019.
"""

import numpy as np

from . import circuits

SHIFT = np.pi / 2


def parameter_shift_gradient(
    n: int,
    depth: int,
    params: np.ndarray,
    cost_fn,
    layer: int = 0,
    qubit: int = 0,
    gate_idx: int = 0,
) -> float:
    params_plus = params.copy()
    params_plus[layer, qubit, gate_idx] += SHIFT
    params_minus = params.copy()
    params_minus[layer, qubit, gate_idx] -= SHIFT

    c_plus = cost_fn(circuits.run_circuit(n, depth, params_plus))
    c_minus = cost_fn(circuits.run_circuit(n, depth, params_minus))
    return (c_plus - c_minus) / 2.0


def finite_difference_gradient(
    n: int,
    depth: int,
    params: np.ndarray,
    cost_fn,
    layer: int = 0,
    qubit: int = 0,
    gate_idx: int = 0,
    eps: float = 1e-6,
) -> float:
    """Central finite difference, used only to cross-check the parameter-shift rule in tests."""
    params_plus = params.copy()
    params_plus[layer, qubit, gate_idx] += eps
    params_minus = params.copy()
    params_minus[layer, qubit, gate_idx] -= eps

    c_plus = cost_fn(circuits.run_circuit(n, depth, params_plus))
    c_minus = cost_fn(circuits.run_circuit(n, depth, params_minus))
    return (c_plus - c_minus) / (2.0 * eps)
