"""Variable-interaction graph (VIG) construction and modularity measurement.

The VIG of a CNF formula has one node per variable and an edge between two
variables for every clause they co-occur in (this is the standard graph
representation used in the SAT community-structure literature, e.g.
Ansotegui et al. 2012, Giraldez-Cru & Levy 2015/2017).
"""

import networkx as nx
from networkx.algorithms.community.quality import modularity


def variable_interaction_graph(cnf):
    """Build the (unweighted-for-modularity-purposes) VIG of a CNF instance."""
    g = nx.Graph()
    g.add_nodes_from(range(1, cnf.n_vars + 1))
    for clause in cnf.clauses:
        vars_in_clause = [abs(lit) for lit in clause]
        for i in range(len(vars_in_clause)):
            for j in range(i + 1, len(vars_in_clause)):
                u, v = vars_in_clause[i], vars_in_clause[j]
                if u == v:
                    continue
                if g.has_edge(u, v):
                    g[u][v]["weight"] += 1
                else:
                    g.add_edge(u, v, weight=1)
    return g


def planted_modularity(cnf):
    """Modularity Q of the formula's own planted community partition against
    its VIG. Returns None if the formula has no planted communities (i.e.
    it was generated by random_3sat rather than community_3sat).

    Q in roughly [-0.5, 1]; higher means the planted partition explains the
    VIG's edges well (few inter-community edges relative to a random graph
    with the same degree sequence).
    """
    if not cnf.communities:
        return None
    g = variable_interaction_graph(cnf)
    # modularity() requires every node to appear in exactly one community
    # and communities to partition the full node set; isolated variables
    # (which can occur when mu is small and a variable is never sampled)
    # still belong to their planted community as a singleton-safe member.
    communities = [set(c) for c in cnf.communities if c]
    return modularity(g, communities, weight="weight")
