name: BuildAndDeployDockerImageToAzureAppService

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: azure/docker-login@v1
              with:
                  login-server: blogger.azurecr.io
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}

            - run: |
                  docker build . -t blogger.azurecr.io/blogger:${{ github.sha }}
                  docker push blogger.azurecr.io/blogger:${{ github.sha }}

            - uses: azure/webapps-deploy@v2
              with:
                  app-name: 'kennethjusino-client'
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: 'blogger.azurecr.io/blogger:${{ github.sha }}'
